### ISSUE TITLE
Some small commentaries

### ISSUE THREAD

**Issue by GusRiva** [hcayless/P3-processing#1]
1. [Line 471 and 472](https://github.com/hcayless/P3-processing/blob/2a591fbe215816d5d8272209c47aa0e2549c8861/articles/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial-2.xml#L471 ): Is the type="#corrections" correct? this is not a pointer, right?

2. Why do editions 2 and 3 have `<ab>` while the first one `<div type="textpart">` ? I thought the latter is the common epidoc.

3. Shouldn't we also transform some infomation in the teiHeader of the epidoc documents? That information is now only in the body of the article as a table which is ok for the creation of the article view, but then someone would need to manually move the information from those tables to the epidoc-TEI.

**Comment by jcowey** [comment]
Information should be made available within the docx file to enable capturing TEI information of already published texts
