### ISSUE TITLE
place-Attribute in Notes

### ISSUE THREAD

**Issue by GusRiva** [hcayless/P3-processing#10]
We don't need a place attribute in the note elements. Also, it is irrelevant for a born digital document. Actually, our viewer can display them to the side of the text.

**Comment by hcayless** [comment]
If there will be only one type of note, I can strip the `@place` if that's desirable.

**Comment by GusRiva** [comment]
I think that would be desirable.
@jcowey would that be ok with you?

**Comment by jcowey** [comment]
Only of one type.
