### ISSUE TITLE
Tables for papyri information

### ISSUE THREAD

**Issue by GusRiva** [hcayless/P3-processing#11]
Right now the bibliographical information of each papyri is encoded in a table before the edition, example: 
```
<table>
   <row>
      <cell>P.Mich. inv. 1986</cell>
      <cell>19 x 10.25 cm</cell>
      <cell>  Apias</cell>
   </row>
   <row>
      <cell>Acquired in 1924</cell>
      <cell/>
      <cell>27 Jan. – 28 Oct., 7 CE</cell>
   </row>
</table>
```

I don't really understand why this structure, as this is not really a table, just a series of items that should be read one after the other. Why not just make paragraphs or a list?

**Comment by hcayless** [comment]
It's a table in the source, so it's a table in the output :-). Representing this kind of info in a tabular form isn't unreasonable, I think. But if something different is wanted, either in the source or the output, tell me and I can do it.

**Comment by jcowey** [comment]
Note to self, do we want the standard "accepted" display of a "papyrological header" or could it be a list?

**Comment by jcowey** [comment]
Stick to standard way.

**Comment by jcowey** [comment]
Alignment could be preserved in output if that is desirable.
