### ISSUE TITLE
ab with line-breaks

### ISSUE THREAD

**Issue by GusRiva** [hcayless/P3-processing#12]
There are sometimes text with line-breaks, like: 
```
 <ab>
and on the 10th of Tybi four dr. = 4 dr.,
and on the 30th of Tybi four dr. = 4 dr.,
and on the 29th of Pharmouthi four dr . = 4 dr., 
and on the 30th of Pharmouthi four dr. = 4 dr.,  
and on the [21-29th] of Pauni twelve dr. = 12 dr.,
and on the 28th of Epeiph eight dr., ½ obol, 2 chalkoi = 8 dr., ½ obol, 2 chalkoi.”
</ab>
```

The line-breaks will disappear in the HTML view. Is that the goal? Otherwise, each line should be embedded in an element, for example:
```
 <ab>
<p>and on the 10th of Tybi four dr. = 4 dr.,</p>
<p>and on the 30th of Tybi four dr. = 4 dr.,</p>
<p>and on the 29th of Pharmouthi four dr . = 4 dr., </p>
<p>and on the 30th of Pharmouthi four dr. = 4 dr.,  </p>
<p>and on the [21-29th] of Pauni twelve dr. = 12 dr.,</p>
<p>and on the 28th of Epeiph eight dr., ½ obol, 2 chalkoi = 8 dr., ½ obol, 2 chalkoi.”</p>
</ab>
```

**Comment by hcayless** [comment]
Formatting for HGV translations in papyri.info is a bit of a mess. I could easily do `<lb/>`s for lines. There is a Leiden+-style conversion for it, but it makes me a little unhappy. The HGV style uses `<milestone>` to mark line beginnings with `@n` to indicate when a line number should be printed. It's often not convenient/suitable to match the translation line-for-line with the source. See, for example, https://papyri.info/ddbdp/bgu;1;4. Anyway, the upshot is that P3 should make some decisions about what conventions you want for translations and I can then generate markup to support that.

**Comment by jcowey** [comment]
This is concerned with points raised in #7.

**Comment by jcowey** [comment]
Decision, as decided in discussion with Rodney Ast (27.01.2021), is to use the Leiden+ style conversion as used in papyri.info
https://github.com/papyri/xsugar/blob/master/translation_epidoc.xsg
as long as that is acceptable for other parties. 
With this Leiden+ style the type of milestone `<milestone unit='line' n='\d+' rend='break'/>` makes it possible to adopt line by line translation where desired and appropriate. The display in papyri.info can be seen at:
http://papyri.info/ddbdp/basp;53;125_1
for the XML see
https://github.com/papyri/idp.data/blob/master/HGV_trans_EpiDoc/703274.xml#L50-L61
