### ISSUE TITLE
Footnote1

### ISSUE THREAD

**Issue by jcowey** [hcayless/P3-processing#2]
Footnote 1 seems not to have been picked up. It is a footnote on the title of the article, which is at:
https://github.com/hcayless/P3-processing/blob/main/articles/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial-2.xml#L42

In the following code line43
https://github.com/hcayless/P3-processing/blob/main/articles/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial-2.xml#L43
the first footnote `<note place="foot" xml:id="ftn2" n="2">` is numbered. 
I searched for `<note place="foot" xml:id="ftn1" n="1">` to no avail.

**Comment by jcowey** [comment]
Footnote 1 is at the end of the first sentence of the article in the version of it that is in this project:
`... all from the Arsinoite nome (see Table 1). 1`
https://github.com/hcayless/P3-processing/blob/main/sources/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial-2.docx?raw=true

I suspect that I put it there because I did not know what to do with a footnote on the title of the article.

**Comment by hcayless** [comment]
Fixed.
