### ISSUE TITLE
Author, affiliation, email missing in file

### ISSUE THREAD

**Issue by jcowey** [hcayless/P3-processing#20]
In the docx file
https://github.com/hcayless/P3-processing/blob/main/sources/ExampleEditionClaryssePrep.docx
there is mark up for author, affiliation, email.
This is apparently not being picked up in:
https://github.com/hcayless/P3-processing/blob/main/articles/ExampleEditionClaryssePrep.xml

Author, affiliation, email IS being picked up and encoded in:
https://github.com/hcayless/P3-processing/blob/main/articles/SPP_22-60_revisited_ra_work_prep.xml#L12-L16
from
https://github.com/hcayless/P3-processing/blob/main/sources/SPP_22-60_revisited_ra_work_prep.docx

Is it because 
#articleTitle is in a different position in the relevant .docx files?

#articleTitle at very first position in 
https://github.com/hcayless/P3-processing/blob/main/sources/SPP_22-60_revisited_ra_work_prep.docx

#articleTitle follows #author, #affiliation, #email in
https://github.com/hcayless/P3-processing/blob/main/sources/ExampleEditionClaryssePrep.docx

**Comment by hcayless** [comment]
That is indeed the reason. `#articleTitle` has to come first in the current setup. If you want that to be optional, let me know. I've modified the Clarysse article, and they're being picked up now.

**Comment by jcowey** [comment]
No I think that it is probably better to have a fixed order in this case.

**Comment by hcayless** [comment]
Seems to be working now.
