### ISSUE TITLE
author forename surname

### ISSUE THREAD

**Issue by jcowey** [hcayless/P3-processing#21]
As of now in 
https://github.com/hcayless/P3-processing/blob/main/articles/SPP_22-60_revisited_ra_work_prep.xml#L12-L16
and
https://github.com/hcayless/P3-processing/blob/main/articles/SPP_22-60_revisited_ra_work_prep.xml#L12-L16

we have e.g.
```
            <author>
               <name>Bagnall, Roger S. </name>
               <affiliation>ISAW, New York</affiliation>
               <email>rsb331@nyu.edu</email>
            </author>
```

Preferable would be (in https://github.com/papyri/idp.data/tree/master/Biblio we separate forename and surname, so it would be helpful to have this work done at this stage in the journal)

```
            <author>
               <name>
                   <forename>Roger S.</forename>
                   <surname>Bagnall</surname>
               </name>
               <affiliation>ISAW, New York</affiliation>
               <email>rsb331@nyu.edu</email>
            </author>
```

Would you please tweak the processing code to make this the standard. In #13 the mark up rule for the word-processed text of any article is:

- #author 
surname COMMA forename(s)

So any name / names (with hyphens, white space in the case of Spanish double names) before the comma will be the surname.
After the comma all names or letters (for abbreviated names) belong to the forename(s)

**Comment by jcowey** [comment]
Looks good now, thank you. One little quibble:
https://github.com/hcayless/P3-processing/blob/main/articles/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4.xml#L9-L14

The coded seems to be producing an unused tag
```
            <author>
               <name>
                  <forename/>
                  <surname/>
               </name>
            </author>
```

**Comment by hcayless** [comment]
Fixed now. I forgot Word puts in an `<author>` tag in its output.
