### ISSUE TITLE
Tweak to XML output

### ISSUE THREAD

**Issue by jcowey** [hcayless/P3-processing#22]
In e.g. https://github.com/hcayless/P3-processing/blob/main/articles/ExampleEditionClaryssePrep/ExampleEditionClaryssePrep.xml#L58-L59:

instead of having the XSLT produce: 
```
               <div copyOf="#ed1"/>
               <div copyOf="#trans1"/>
```

would you please make it produce
```
               <div type="edition" copyOf="#ed1"/>
               <div type="translation" copyOf="#trans1"/>
```

That would make the source github code easier for the UB-Heidelberg team easier to use for the transformation into their XML. See the mail exchange from 12./14. May 2021 between Maylein and Cowey.

**Comment by hcayless** [comment]
Should be done.
