### ISSUE TITLE
Figure, graphic details

### ISSUE THREAD

**Issue by jcowey** [hcayless/P3-processing#23]
https://github.com/hcayless/P3-processing/blob/main/articles/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4.xml#L270-L276

```
               <figure>
                          <graphic n="1001"
                                   width="15.239647222222223cm"
                                   height="1.5466694444444444cm"
                                   url="media/image1.jpeg"/>
                          <head>Fig. 1. P.Mil. 12.9, line 3. Image published courtesy of the Direzione della Biblioteca di Atene dell'Università Cattolica del Sacro Cuore di Milano.   </head>
               </figure>
```

Why the number at @n? These do not need to be displayed, do they? Only "1" appears.
- @width and @height indicate the measurements for the display. Do the numerals after the comma come about through conversion from inches?

**Comment by hcayless** [comment]
Don't know why the `@n`. A assume it's automatically generated. I can get rid of it.

I expect the width and height are derived from the dimensions in the document. I've no idea whether it's assuming an 8.5' x 11' document and converting to cm or assuming A4, and the dimensions are just weirdly specific...probably the former. I think the question of whether to keep them is probably for the Library folks to answer. Knowing the aspect ratio might be useful, but you can get that from the image itself. I'm happy to remove them, or there may be ways to configure for different units (or I can easily round them off).

**Comment by lmaylein** [comment]
I don't think this is a question of whether we leave the attributes in the TEI, rather a question of whether they should or must have an effect on the visualization.
I would leave them for now. They don't do any harm. Maybe we need to consider them more in PDF generation.

**Comment by jakub-simek** [comment]
And what about the `@n` with the strange values like "1001"? I suppose there might be good reasons to have an explicit numbering on figures, but then we would expect the `@n` on `<figure>`, not `<graphic>`.  

If however the figure number is stated "by hand" in the `<head>` anyway, we don't really need it in this form on `<graphic>`. What would be needed though is `@xml:id` (on `<figure>`) if authors were supposed or allowed to refer to single figures by something like `<ref>` inside their running text and if we were expected to render this as URL links.

**Comment by lmaylein** [comment]
@jakub-simek : Every figure, table or p tag without an ID automatically gets an xml:id during our transformation.

**Comment by jakub-simek** [comment]
> @jakub-simek : Every figure, table or p tag without an ID automatically gets an xml:id during our transformation.

Sure, but if the authors were to refer to figures in the Word documents already, then they already would need some sort of identifier. But we can approach this in due time when/if such a case arises at all.
