### ISSUE TITLE
Head: papyrological header info missing

### ISSUE THREAD

**Issue by jcowey** [hcayless/P3-processing#24]
It appears that somewhere in the pipeline the information for the papyrological header is no longer being transformed into XML.

Here is an old version of the file:
https://github.com/hcayless/P3-processing/commit/e3af1eed53e2dd7301849a1b5b1fc1553d8fded9#diff-b2f9d2d3b0029f3309d7777c337e73920099d93c80fc9213e053194d6ade042cR166-R181

This is the new one:
https://github.com/hcayless/P3-processing/blob/main/articles/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4.xml#L173-L182

Between https://github.com/hcayless/P3-processing/blob/main/articles/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4.xml#L173-L174

the `head` information should be generated and included in the XML

**Comment by jcowey** [comment]
In ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4.docx
the `Papyrological Header` information is to be found:

```
1. Receipt for Syntaxis

P.Heid.inv. G 1026 | 13.5 x 10 cm | Theadelphia,
-- | -- | --
Acquired in 1959 | &nbsp; | Nov., 16 – Aug., 15 BCE

```

**Comment by jcowey** [comment]
table type="papyrological_header"

do not output in a head.

**Comment by hcayless** [comment]
Should be fixed

**Comment by jcowey** [comment]
This is what we used to have:
```
                  <head>1. Receipt for Syntaxis<note place="foot" xml:id="ftn10" n="10">
                        <p style="text-align:; "> Claytor wishes to thank Andrea Jördens for permission to publish this papyrus and Roger Bagnall for commenting on a draft transcription.</p>
                     </note>
                     <table>
                        <row>
                           <cell>P.Heid.inv. G 1026</cell>
                           <cell>13.5 x 10 cm</cell>
                           <cell>  Theadelphia,</cell>
                        </row>
                        <row>
                           <cell>Acquired in 1959</cell>
                           <cell/>
                           <cell>Nov., 16 – Aug., 15 BCE</cell>
                        </row>
                     </table>
                  </head>
```

Cf. also (fixed by hand): 

https://gitlab.ub.uni-heidelberg.de/verlag/PapyrologicalPublicationPlatform/-/blob/master/epidoc/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4.xml#L176-191

Which is producing nice results: 


What we have here:
https://github.com/hcayless/P3-processing/blob/main/articles/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4.xml#L174-L219

seems to conflate, I think, data from the papyrological header with information from the HGV meta. 

I am actually on holiday so do not have as much time to look at this.

**Comment by hcayless** [comment]
Think this is properly fixed now.
