### ISSUE TITLE
Marking individual editions within one article

### ISSUE THREAD

**Issue by jcowey** [hcayless/P3-processing#28]
What do we want the mark up for each div to look like for each new "text"

**Comment by jcowey** [comment]
An example:
https://github.com/hcayless/P3-processing/blob/main/articles/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4.xml#L173

```
<div type="epidoc" subtype="DDB">
```

could become
```
<div type="epidoc" subtype="DDB" n="1">
```

**Comment by jcowey** [comment]
Cf. the comment `Every figure, table or p tag without an ID automatically gets an xml:id during our transformation` in #23

**Comment by jcowey** [comment]
By way of comparison `#articleHeader` is converted to `<div type="section">` at

https://github.com/hcayless/P3-processing/blob/main/articles/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4.xml#L215

this becomes `<div type="section">` at

https://gitlab.ub.uni-heidelberg.de/verlag/PapyrologicalPublicationPlatform/-/blob/master/epidoc/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4.xml#L213

**Comment by jcowey** [comment]
do we want to re-consider using the mark up `#editionHeader` in the word processing files that are used as a basis for P3 conversion.

**Comment by hcayless** [comment]
Leave this alone until/unless we decide we need it.
