### ISSUE TITLE
Mark up for paragraphs in div commentary

### ISSUE THREAD

**Issue by jcowey** [hcayless/P3-processing#29]
Use of note with paragraphs inside. 
Possibility of ref and target for the paragraph elements to make the reference to the lb tag in the relevant text explicit.

**Comment by jcowey** [comment]
List of notes and those notes can have multiple paragraphs. Id generation.

**Comment by hcayless** [comment]
With f23d3f775358eb9345fa64328d784255dc60e28b, notes (including multi-paragraph notes) should be wrapped in `<note>`s. There will be in TEI a `<listNote>` element (probably in the next release) which would be a good candidate for this type of thing, but it's not available yet.
