### ISSUE TITLE
No <p> tags in tables

### ISSUE THREAD

**Issue by jcowey** [hcayless/P3-processing#31]
At https://github.com/hcayless/P3-processing/blob/main/articles/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4.xml#L111-L112

we have

```
<cell style="text-align: left;">
   <p xml:id="p6">a: Romulus (χειριστής) </p>
   <p xml:id="p7">b: Mysthes (λογευτής)</p>
</cell>
```

The two `<p>` tags should not be there. Can you please ignore / process differently in such cases. The existence of the `<p>` tag leads to them being displayed as paragraphs, which is not wanted.

**Comment by lmaylein** [comment]
For p tags within tables, a paragraph number is now no longer displayed.
