### ISSUE TITLE
Hyperlinks not coming through

### ISSUE THREAD

**Issue by jcowey** [hcayless/P3-processing#34]
Uploaded a new, prepared article
Schubert_liturgy_pylon_hgv_formatted_4t.docx
to

https://github.com/hcayless/P3-processing/blob/main/sources/

where you can see it:

https://github.com/hcayless/P3-processing/blob/main/sources/SPP_22-60_revisited_ra_work_prep.docx

It processed (discursive paragraphs with hyperlinks and two big tables, NO Greek or Latin text editions, bibliography).

The hyperlinks in the .docx file have not been picked up and put in the ref tag.
e.g.:
https://github.com/hcayless/P3-processing/blob/main/articles/Schubert_liturgy_pylon_hgv_formatted_4t/Schubert_liturgy_pylon_hgv_formatted_4t.xml#L69

**Comment by hcayless** [comment]
This should be fixed. There was a bug in the TEI Stylesheets.
