### ISSUE TITLE
Differentiation of table types

### ISSUE THREAD

**Issue by lmaylein** [hcayless/P3-processing#35]
@hcayless , @jcowey , @jakub-simek 
How can we distinguish the different types of tables (normal tables in the text vs. header information for editions/papyri)? These are supposed to get different layouts.

**Comment by jakub-simek** [comment]
Is there an example for the second type somewhere in the TEI files?

Or would the second type be generated from the teiHeader metadata?

**Comment by lmaylein** [comment]
> Is there an example for the second type somewhere in the TEI files?
> 
> Or would the second type be generated from the teiHeader metadata?

https://github.com/hcayless/P3-processing/blob/4471d059bb5de6bf23b3ea8df6b64d5c22e8809d/articles/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial_4.xml#L248

**Comment by lmaylein** [comment]
@jakub-simek Thanks for asking....  type="papyrological_header"... This is apparently still missing from the file in our gitlab.
