### ISSUE TITLE
Tripped on articleTitle

### ISSUE THREAD

**Issue by jcowey** [hcayless/P3-processing#38]
Uploaded a re_marked_up docx file
https://github.com/hcayless/P3-processing/commit/3795f79aa520b6bd9a4efe1fd0fd79978f466bd2

The article title is not as I expected to see it:

https://github.com/hcayless/P3-processing/blob/main/articles/Messeri_pylon1_prep_jan_2022/Messeri_pylon1_prep_jan_2022.xml#L8

and

https://github.com/hcayless/P3-processing/blob/main/articles/Messeri_pylon1_prep_jan_2022/Messeri_pylon1_prep_jan_2022.xml#L49

appear to have done different things with:

"Ricevuta di pagamento del πελωχικόν" in the word document

Am I failing to see something wrong with my mark up?

**Comment by hcayless** [comment]
@jcowey look at it now. The title is weird: everything bolded except the omicron in πελωχικόν. I imagine that's not what you really want, but it's doing what it's told.  The code was assuming all titles would be plain text, and that's again what you're getting in the `<title>` with the current fix. Let me know if that's incorrect.

**Comment by jcowey** [comment]
https://github.com/hcayless/P3-processing/blob/main/articles/Messeri_pylon1_prep_jan_2022/Messeri_pylon1_prep_jan_2022.xml#L8

now looks good and what I hoped to see.

Shall try to remember to check for plain text. Plain text means no bold, italics etc? Greek is OK, isn't it.

**Comment by hcayless** [comment]
I wouldn't want to outlaw, e.g., italicizing a word in a title. I guess it depends how it might be used. Instinctively it feels to me like `<title>` is something that might go into a database field or something like that (and thus need to be plain text), but that might just be my own prejudices talking. This particular title is formatted in a funny way though, so it probably needs a little attention. Greek, Coptic, Arabic, whatever is fine in a title.
