### ISSUE TITLE
Bibliography slip

### ISSUE THREAD

**Issue by jcowey** [hcayless/P3-processing#39]
This is what happened to the bibliography section for the Messeri article:

https://github.com/hcayless/P3-processing/blob/main/articles/Messeri_pylon1_prep_jan_2022/Messeri_pylon1_prep_jan_2022.xml#L103-L120

Looks very good, apart from 
https://github.com/hcayless/P3-processing/blob/main/articles/Messeri_pylon1_prep_jan_2022/Messeri_pylon1_prep_jan_2022.xml#L107

`</listBibl>` should close in code line 120

after

https://github.com/hcayless/P3-processing/blob/main/articles/Messeri_pylon1_prep_jan_2022/Messeri_pylon1_prep_jan_2022.xml#L119

Is there something wrong with the mark up in the docx file?

**Comment by hcayless** [comment]
Just a bug. Fixed.
