### ISSUE TITLE
paragraph numbering in note tag

### ISSUE THREAD

**Issue by jcowey** [hcayless/P3-processing#40]
Can we please continue the `xml:ids` on the `<p>` tags in the commentary section. Numbering continues from 

`p10` 

in 

https://github.com/hcayless/P3-processing/blob/main/articles/Messeri_pylon1_prep_jan_2022/Messeri_pylon1_prep_jan_2022.xml#L78

**Comment by hcayless** [comment]
Should be fixed.

**Comment by jcowey** [comment]
https://github.com/hcayless/P3-processing/blob/main/articles/Messeri_pylon1_prep_jan_2022/Messeri_pylon1_prep_jan_2022.xml#L85

and 

https://github.com/hcayless/P3-processing/blob/main/articles/Messeri_pylon1_prep_jan_2022/Messeri_pylon1_prep_jan_2022.xml#L88

and code lines 91, 94, 95, 98, 101

all have `<p xml:id="p11">`

I presume that is a tiny bug. I reckoned they should start with p11 then continue p12, p13 etc.

**Comment by hcayless** [comment]
Yeah, I fixed one bit but not the corresponding id computation. Now it really is fixed.
