### ISSUE TITLE
Invalid numeric literal error

### ISSUE THREAD

**Issue by jcowey** [hcayless/P3-processing#52]
I uploaded a file to https://github.com/hcayless/P3-processing/tree/main/sources

https://github.com/hcayless/P3-processing/blob/main/sources/ferretti_corrections_prep.docx

`ferretti_corrections_prep.docx` had a Leiden+ mistake, so do not use this one! use `ferretti_corrections3_prep.docx`

got the following error message: https://github.com/hcayless/P3-processing/actions/runs/9694364594/job/26751799835

tried again: https://github.com/hcayless/P3-processing/blob/main/sources/ferretti_corrections1_prep.docx

no change: https://github.com/hcayless/P3-processing/actions/runs/9694544727/job/26752404637

tried again: https://github.com/hcayless/P3-processing/blob/main/sources/ferretti_corrections2_prep.docx

no change: https://github.com/hcayless/P3-processing/actions/runs/9694696046/job/26752883429

tried again: https://github.com/hcayless/P3-processing/blob/main/sources/ferretti_corrections3_prep.docx

no change: https://github.com/hcayless/P3-processing/actions/runs/9695016162/job/26753877853

Error message is:

BUILD SUCCESSFUL
Total time: 2 seconds
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
Leiden+ conversion failed for sources/ferretti_corrections3_prep.docx.

I have checked the Leiden+ of the #text section in the Editor where it is fine.

Not sure that I have ever had `parse error: Invalid numeric literal at line 1, column 7` as an error message.

Googled it. Am no further forward in solving my problem. If you can solve and convert `ferretti_corrections3_prep.docx` for me I would be most grateful.

**Comment by jcowey** [comment]
Would also be grateful if you would point out the error to me / explain it, so that I may be able to solve similar things in the future.

**Comment by samosafuz** [comment]
I've tried my hand at this too, with no success. `Line 981 `of the [error message](https://github.com/hcayless/P3-processing/actions/runs/9698063123/job/26763727778) suggests a Leiden+ error (i.e., XSugar conversion) is responsible, but I have confirmed that the Leiden+ is good.

**Comment by hcayless** [comment]
The address for the XSugar service changed as the result of a migration yesterday. The service the old one was hosted on is being decommissioned. So the error message was reacting to an error response from the old URL. I've updated it in the script.
