### ISSUE TITLE
section-Tagging

### ISSUE THREAD

**Issue by lmaylein** [hcayless/P3-processing#6]
The tagging of the chapters seems different to me (sometimes `div/@type=section` is missing, sometimes `head` is within `div@type=epidoc`). Is this one the right nesting of the tags?

```
            <div type="section">
               <head>3-4. Poll Tax Receipts from the Harthotes Archive</head>
               <div type="epidoc">
```

**Comment by hcayless** [comment]
It is different. editions 3 and 4 are grouped in the source document and have their own subheading. 1 and 2 are not treated that way.

**Comment by lmaylein** [comment]
I'm not sure I've got that right. There are only four sections in this article, namely those with the following headings?

 * Table 1. Poll Tax Receipts on Papyrus, 30 BCE – 37 CE
 * 3-4. Poll Tax Receipts from the Harthotes Archive
 * Appendix: Rereading P.Mil. 12.9 (Claytor)
 * Appendix: Rereading P.Mil. 12.9 (Claytor)

@jcowey ?

**Comment by hcayless** [comment]
The "Table 1." heading is an error. That should be picked up as a table caption rather than a section heading. "3-4..." is correctly a section heading though (at least as the document is currently formatted).

**Comment by hcayless** [comment]
Apologies, I was confused by https://github.com/hcayless/P3-processing/blob/e3af1eed53e2dd7301849a1b5b1fc1553d8fded9/articles/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial-3.xml#L67-L72, which I think is incorrect. That heading is a table caption, correctly handled in https://github.com/hcayless/P3-processing/blob/e3af1eed53e2dd7301849a1b5b1fc1553d8fded9/articles/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial-2.xml#L67-L71 (I could be convinced that the whole thing should be wrapped in a `<figure>`). I think the correct section headings are:
```xml
<head>3-4. Poll Tax Receipts from the Harthotes Archive</head>
```
and
```xml
<head>Appendix: Rereading P.Mil. 12.9 (Claytor)</head>
```
By "correct", I mean correct given the input, not necessarily right. I do not think the table caption is a section heading though.

**Comment by jcowey** [comment]
https://github.com/hcayless/P3-processing/blob/main/articles/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial-3.xml#L67-L72
```
            <div type="section">
               <head>Table 1. Poll Tax Receipts on Papyrus, 30 BCE – 37 CE<note place="foot" xml:id="ftn9" n="9">
                     <p style="text-align:; "> The two orders to issue poll-tax receipts, recently (re)edited by Hagedorn, should be considered together with these receipts: Hagedorn 2013 (n. 7).</p>
                  </note>
               </head>
               <table>
```
was a result of a change made by me to the mark up of the .docx file and then pushed through the processing. 
I mentioned this in #4.
I had thought that the "Table 1. Poll Tax Receipts on Papyrus, 30 BCE – 37 CE" was a `head` and at the same level as the other `head` tags. One can argue about this, but maybe you are right, Hugh.

**Comment by lmaylein** [comment]
Okay, this is the table caption. Does this mean that there will also be sections (like this) without titles, which will then also not be listed in the table of contents?
