### ISSUE TITLE
xml:id for paragraphs, sections, ...?

### ISSUE THREAD

**Issue by lmaylein** [hcayless/P3-processing#8]
Our viewer (heiVIEWER) allows us to offer persistent URLs for sections and paragraphs, etc. These are also used when specific text passages are to be annotated. For this, it is necessary that chapters and paragraphs have an `xml:id` attribute. We can create these attributes in our workflow (sequential numbering). However, if the editors want specific (meaningful) IDs, these would have to be generated in a different way.

**Comment by hcayless** [comment]
I can easily add paragraph ids. Will do.

**Comment by jcowey** [comment]
Yes addition of paragraph ids is great.
