### ISSUE TITLE
Article Title as docTitle

### ISSUE THREAD

**Issue by GusRiva** [hcayless/P3-processing#9]
Could we move the article title from the head to 
```
<text>
     <front>
         <docTitle>
            <titlePart type="MainTitle">Four Poll-Tax Receipts on Papyrus from the Early-Roman Fayum</titlePart>
         </docTitle>
     </front>
    <body>
    [....]
```

**Comment by hcayless** [comment]
Sure. If you want articles to have a "title page" we might need to have the source document reflect that, but if you want it, tell me.

**Comment by GusRiva** [comment]
It would be desirable for us - something less we need to transform.
@jcowey would that be ok for you?

**Comment by jcowey** [comment]
I think that the title really belongs in the `titleStmt/title` right at the beginning, as I had suggested in:
https://github.com/jcowey/P3/blob/master/data/claytor.xml#L7-L45
```
            <titleStmt>
                <title>Four poll-tax receipts on papyrus from the Early-Roman Fayum</title>
                <respStmt>
                    <resp>author</resp>
                    <name>
                        <persName n="1">
                            <forename>W. Graham</forename>
                            <surname>Claytor</surname>
                        </persName>
                        <affiliation>
                            <orgName>Universität Basel</orgName>
                            <placeName>Basel</placeName>
                        </affiliation>
                        <email>mustermann543@gmail.com</email>
                    </name>
                    <name>
                        <persName n="2">
                            <forename>Richard</forename>
                            <surname>Warga</surname>
                        </persName>
                        <affiliation>
                            <orgName>Louisiana State University</orgName>
                            <placeName>Baton Rouge</placeName>
                        </affiliation>
                        <email>mustermann54@gmail.com</email>
                    </name>
                    <name>
                        <persName n="3">
                            <forename>Zachary G.</forename>
                            <surname>Smith</surname>
                        </persName>
                        <affiliation>
                            <orgName>Yale University</orgName>
                            <placeName>New Haven</placeName>
                        </affiliation>
                        <email>mustermann5@gmail.com</email>
                    </name>
                </respStmt>
            </titleStmt>
```

This means that the mark up to be added to the `.docx` version has to be made explict for 
- title (can `title` have a note[something I would like to avoid, but often used in papyrological publications])
- author(s) with affiliation and email if desired

**Comment by jcowey** [comment]
After discussion between Hugh and myself, I understand that the title of the article can be used in `titleStmt/title` but certainly does not have to be. Leaving that aside for the present, I have no problems with using the XML suggested above by @GusRiva. So, yes, @hcayless, please tweak the processing to produce. 
```
<text>
     <front>
         <docTitle>
            <titlePart type="MainTitle">Four Poll-Tax Receipts on Papyrus from the Early-Roman Fayum</titlePart>
         </docTitle>
     </front>
    <body>
    [....]
```

**Comment by hcayless** [comment]
So one question here: the sample article has a footnote on the title. Is that ok in your system?

**Comment by GusRiva** [comment]
Sorry for the late answer. We had a complex discussion about this.
We would prefer to avoid footnotes in the main title of the article. I can't find the example file, though. What is that footnote about? For acknowledgements, for example, we have a dedicated element.

Also, now I'm wondering: is this title the same as the title in the teiHeader?

**Comment by hcayless** [comment]
@GusRiva Sorry for the late response to your question. Yes, as things stand, the title will be replicated in the teiHeader of the article. We also had a followup question about author info: will you want that in the front matter as well? It too will go in the header.
